version: 2

jobs:

    generate_dox:
        docker:
            - image: marzer/cpp_dev:0.1.0
        resource_class: small
        steps:
            - checkout
            - run:
                name: Installing dependencies
                command: |
                    pip3 install -r requirements.txt
            - run:
                name: Generating documentation
                command: |
                    poxy --verbose
            - persist_to_workspace:
                root: .
                paths: html

    deploy_dox:
        docker:
            - image: node:14.4.0
        resource_class: small
        steps:
            - checkout
            - attach_workspace:
                at: .
            - run:
                name: Disable jekyll builds
                command: |
                    touch html/.nojekyll
            - run:
                name: Installing dependencies
                command: |
                    npm install -g --silent gh-pages@3.0.0
                    git config user.email "ci-build@marzer.github.io"
                    git config user.name "ci-build"
            - add_ssh_keys:
                fingerprints:
                    - "ae:e8:31:02:fc:41:43:44:48:47:4c:08:77:fb:14:f0"
            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dotfiles --message "[skip ci] Updates" --dist html

workflows:
    version: 2
    build:
        jobs:
            - generate_dox:
                filters:
                    branches:
                        only: main
            - deploy_dox:
                requires:
                    - generate_dox
