name: gh-pages

on:
    push:
        branches:
            - main
        paths:
            - "**.h"
            - "**.hpp"
            - "**.dox"
            - "**.md"
            - "docs/**"
            - "fitness/**"
            - "poxy.toml"
            - ".github/workflows/gh-pages.yaml"
    workflow_dispatch:

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        steps:
            - uses: actions/checkout@v7

            - name: Install dependencies
              run: |
                  sudo apt -y update
                  sudo apt -y install --no-install-recommends git python3 python3-pip doxygen dvisvgm
                  sudo -H pip3 install --upgrade poxy markdown

            - name: Generate docs
              run: |
                  poxy --verbose

            - name: Generate fitness site
              run: |
                  python3 fitness/build.py

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./html
